version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always    
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/default.conf
      - ./docs/html:/var/www/localhost/html
    ports:
      - "80:80"
    command: /bin/bash -c "exec nginx -g 'daemon off;'"