# Generated by Django 3.0.5 on 2020-04-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
