# Generated by Django 3.0 on 2020-03-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('appointment', '0002_appointment_serviceprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='serviceProvider',
        ),
        migrations.AddField(
            model_name='appointment',
            name='serviceProvider',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.Business'),
            preserve_default=False,
        ),
    ]
