# Generated by Django 3.0 on 2020-03-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20200329_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='serviceProvider',
            new_name='service_provider',
        ),
    ]
