# Generated by Django 3.0 on 2020-04-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200329_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='telephone_number',
            new_name='phone_number',
        ),
    ]
